# Simpler but require CRONJOB to sync DAGs from S3 to EFS
# AND manual sync at first time
airflow:
  executor: CeleryExecutor
  config:
    AIRFLOW__CORE__FERNET_KEY: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="  # Replace with your actual
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  dags:
    path: /opt/airflow/dags
    persistence:
      enabled: true
      existingClaim: airflow-efs-dags  # Use the existing EFS PVC
    gitSync:
      enabled: false
  logs:
    persistence:
      enabled: true
  scheduler:
    replicas: 1
  webserver:
    replicas: 1
  workers:
    replicas: 1
    # Ensure workers mount the DAGs PVC
    persistence:
      enabled: true
      existingClaim: airflow-efs-dags
  dagProcessor:
    enabled: true

# PostgreSQL configuration to fix OpenShift security context issues
postgresql:
  primary:
    containerSecurityContext:
      enabled: true
      runAsUser: null  # Let OpenShift assign the user
      runAsNonRoot: true
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      seccompProfile: null  # Remove seccomp profile for OpenShift compatibility
